### ISSUE TITLE
MW2 Steam Fails

### ISSUE THREAD

**Issue by TheBorn** [sheilan102/husky_modified#23]
Found supported game: Call of Duty: Modern Warfare 2 - This is error I get on Multiplayer.

Parsing IWD files...
Parsing map data...

Parsing light data...
Parsed light data in 0.00 seconds.
Parsing map geometry...
Parsed map geometry in 1.67 seconds.
Parsing map models...
An unhandled exception has occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at C2M.ModernWarfare2.ReadXModel(ProcessReader reader, MW2XModel modelData, CoDMap codmap, Action`1 printCallback) in C:\work __ dev\C2M_v2\C2M\Games\ModernWarfare2.cs:line 466
   at C2M.ModernWarfare2.ReadStaticModels(ProcessReader reader, Int64 address, Int32 count, CoDMap codmap, Action`1 printCallback) in C:\work __ dev\C2M_v2\C2M\Games\ModernWarfare2.cs:line 423
   at C2M.ModernWarfare2.LoadBSPData(Process process, GameInfo gameInfo, Action`1 printCallback) in C:\work __ dev\C2M_v2\C2M\Games\ModernWarfare2.cs:line 285
   at C2M.HuskyUtil.LoadGame(Action`1 printCallback) in C:\work __ dev\C2M_v2\C2M\HuskyUtil.cs:line 194

Found supported game: Call of Duty: Modern Warfare 2 -- This is for Singleplayer on the map Cliffhanger.

Parsing IWD files...
Parsing map data...

Parsing light data...
Parsed light data in 0.00 seconds.
Parsing map geometry...
Parsed map geometry in 9.55 seconds.
Parsing map models...
An unhandled exception has occured:
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.Path.GetFileNameWithoutExtension(String path)
   at C2M.ModernWarfare2.ReadMaterial(ProcessReader reader, Int64 address, CoDMap codmap) in C:\work __ dev\C2M_v2\C2M\Games\ModernWarfare2.cs:line 376
   at C2M.ModernWarfare2.ReadXModel(ProcessReader reader, MW2XModel modelData, CoDMap codmap, Action`1 printCallback) in C:\work __ dev\C2M_v2\C2M\Games\ModernWarfare2.cs:line 464
   at C2M.ModernWarfare2.ParseDynamicModels(ProcessReader reader, List`1 entities, CoDMap codmap) in C:\work __ dev\C2M_v2\C2M\Games\ModernWarfare2.cs:line 561
   at C2M.ModernWarfare2.LoadBSPData(Process process, GameInfo gameInfo, Action`1 printCallback) in C:\work __ dev\C2M_v2\C2M\Games\ModernWarfare2.cs:line 289
   at C2M.HuskyUtil.LoadGame(Action`1 printCallback) in C:\work __ dev\C2M_v2\C2M\HuskyUtil.cs:line 194

**Comment by sheilan102** [comment]
Try with this https://www.knannou.com/c2m
