### ISSUE TITLE
issue extracting wwii maps

### ISSUE THREAD

**Issue by atomiccrazzy** [sheilan102/husky_modified#27]
so im having an issue to where 1 the map extracts but not the materials or 2 i get this error: 
Generating map files...
An unhandled exception has occured:
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.Path.GetFileNameWithoutExtension(String path)
   at Husky.WorldWarII.ExportBSPData(ProcessReader reader, Int64 assetPoolsAddress, Int64 assetSizesAddress, String gameType, Action`1 printCallback) in D:\my dev projects\C2Mf\Husky\Games\WorldWarII.cs:line 498
   at Husky.HuskyUtil.LoadGame(Action`1 printCallback) in D:\my dev projects\C2Mf\Husky\HuskyUtil.cs:line 94

**Comment by HaveDex** [comment]
I got the same error btw

**Comment by AllusiveWheat** [comment]
You have spaces in your path, make sure you don't have any spaces.

**Comment by atomiccrazzy** [comment]
yea i dont have any spaces in my path since the path thats in that code isnt on my pc anywhere

**Comment by AllusiveWheat** [comment]
What was the path for the extracted files?

**Comment by atomiccrazzy** [comment]
yea this is where it automatically extracted it to E:\cod3d\C2M_v2_RELEASE\exported_images\        and         E:\cod3d\C2M_v2_RELEASE\exported_maps\

**Comment by AllusiveWheat** [comment]
Ok then I have no idea

**Comment by WindowsXPSux** [comment]
Did anyone get this fixed? or am I going to have to recreate that path for it to work?

**Comment by WindowsXPSux** [comment]
Did anyone get this fixed?

**Comment by RaGe-74** [comment]
Still broken Aug. 2024. Rips Geo fine, just not the .map for model placement

Found supported game: Call of Duty: World War II
Loaded Gfx Map     -   maps/mp/mp_prague.d3dbsp
Loaded Map         -   mp_prague
Vertex Count       -   1469558
Indices Count      -   3451980
Surface Count      -   26879
Model Count        -   12257
Parsing vertex data....
Parsed vertex data in 2.43 seconds.
Parsing surface indices....
Parsed indices in 0.00 seconds.
Parsing surfaces....
Parsed surfaces in 0.04 seconds.
Generating map files...
An unhandled exception has occured:
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.Path.GetFileNameWithoutExtension(String path)
   at Husky.WorldWarII.ExportBSPData(ProcessReader reader, Int64 assetPoolsAddress, Int64 assetSizesAddress, String gameType, Action`1 printCallback) in D:\my dev projects\C2Mf\Husky\Games\WorldWarII.cs:line 498
   at Husky.HuskyUtil.LoadGame(Action`1 printCallback) in D:\my dev projects\C2Mf\Husky\HuskyUtil.cs:line 94
