### ISSUE TITLE
c2m export error

### ISSUE THREAD

**Issue by filmedbymatthew** [sheilan102/husky_modified#6]
An unhandled exception has occured:
System.UnauthorizedAccessException: Access to the path 'exported_maps\advanced_warfare\mp\mp_vlobby_room' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)

**Comment by 0x8080** [comment]
make sure you whave read/write access to that file directory

**Comment by filmedbymatthew** [comment]
I checked the permissions by right-clicking on c2m.exe and it says everything is checked and allowed but I still get this error

**Comment by filmedbymatthew** [comment]
Can we chat on social media IG -  @emojimatt_
